### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by ModMaamari** [FarukHammoud/processing_py#2]
When I run your example:

```
from processing_py import *

app = App(600,400) # create window: width, height
app.background(255,0,0) # set background:  red, green, blue
app.redraw() # refresh the window

app.exit() # close the window
```

I get the next warning :

```
Starting App...
>> WARNING: An illegal reflective access operation has occurred

>> WARNING: Illegal reflective access by org.python.core.PySystemState (file:/home/modmari/anaconda3/lib/python3.8/site-packages/processing_py/processing/processing-py.jar) to method java.io.Console.encoding()

>> WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState

>> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

>> WARNING: All illegal access operations will be denied in a future release
```

**Comment by kallebk** [comment]
I used the same example to test...
I got the same warnings. What a pity ... At this moment not working ...
Python 3.7.4 (bundled)
>>> %Run TesteThonneyProcessing.py
Starting App...
>> Exception in thread "main" java.lang.UnsupportedClassVersionError: jycessing/Runner : Unsupported major.minor version 51.0

>> 	at java.lang.ClassLoader.defineClass1(Native Method)

>> 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)

>> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)

>> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)

>> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)

>> 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)

>> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)

>> 	at java.security.AccessController.doPrivileged(Native Method)

>> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)

>> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)

>> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)

>> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)


Traceback (most recent call last):
  File "/Users/admin/Desktop/PythonMandelbrotETC/ThonneyBeispiele/TesteThonneyProcessing.py", line 4, in <module>
    app.background(255,0,0) # set background:  red, green, blue
  File "/Users/admin/Library/Python/3.7/lib/python/site-packages/processing_py/app.py", line 87, in background
    self.std_function('background',*args)
  File "/Users/admin/Library/Python/3.7/lib/python/site-packages/processing_py/app.py", line 76, in std_function
    self.sendLine(s)
  File "/Users/admin/Library/Python/3.7/lib/python/site-packages/processing_py/app.py", line 64, in sendLine
    self.stream.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
>>>

**Comment by FarukHammoud** [comment]
> When I run your example:
> 
> ```
> from processing_py import *
> 
> app = App(600,400) # create window: width, height
> app.background(255,0,0) # set background:  red, green, blue
> app.redraw() # refresh the window
> 
> app.exit() # close the window
> ```
> 
> I get the next warning :
> 
> ```
> Starting App...
> >> WARNING: An illegal reflective access operation has occurred
> 
> >> WARNING: Illegal reflective access by org.python.core.PySystemState (file:/home/modmari/anaconda3/lib/python3.8/site-packages/processing_py/processing/processing-py.jar) to method java.io.Console.encoding()
> 
> >> WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
> 
> >> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> 
> >> WARNING: All illegal access operations will be denied in a future release
> ```

Processing-py uses Jython (a Java implementation of Python), they have this open issue:

https://stackoverflow.com/questions/46230413/jdk9-an-illegal-reflective-access-operation-has-occurred-org-python-core-pysys
https://bugs.jython.org/issue2582

**Comment by FarukHammoud** [comment]
> I used the same example to test...
> I got the same warnings. What a pity ... At this moment not working ...
> Python 3.7.4 (bundled)
> 
> > > > %Run TesteThonneyProcessing.py
> > > > Starting App...
> > > > Exception in thread "main" java.lang.UnsupportedClassVersionError: jycessing/Runner : Unsupported major.minor version 51.0
> 
> > > at java.lang.ClassLoader.defineClass1(Native Method)
> 
> > > at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
> 
> > > at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
> 
> > > at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> 
> > > at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> 
> > > at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> 
> > > at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> 
> > > at java.security.AccessController.doPrivileged(Native Method)
> 
> > > at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> 
> > > at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> 
> > > at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
> 
> > > at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> 
> Traceback (most recent call last):
> File "/Users/admin/Desktop/PythonMandelbrotETC/ThonneyBeispiele/TesteThonneyProcessing.py", line 4, in
> app.background(255,0,0) # set background: red, green, blue
> File "/Users/admin/Library/Python/3.7/lib/python/site-packages/processing_py/app.py", line 87, in background
> self.std_function('background',*args)
> File "/Users/admin/Library/Python/3.7/lib/python/site-packages/processing_py/app.py", line 76, in std_function
> self.sendLine(s)
> File "/Users/admin/Library/Python/3.7/lib/python/site-packages/processing_py/app.py", line 64, in sendLine
> self.stream.stdin.flush()
> BrokenPipeError: [Errno 32] Broken pipe
> 
> > > >

It needed admin permission to access a file that contained variables like mouseX, mouseY, etc. But version 0.3.* corrected it so you don't need to run it as admin anymore. You can upgrade your version using pip install processing-py --upgrade

**Comment by kallebk** [comment]
Thanks for the upgrade to processing-py 0.3.1. It is still not working, again errors appear...
:-(
I use Thonney 3.3.1 , a python IDE, https://thonney.org, where you can easily install 
packages from: Install from PyPI.
Thonney says ist uses Python 3.7.9
I use this example
--------------
from processing_py import *

app = App(600,400) # create window: width, height
app.background(0,0,0) # set background:  red, green, blue
app.fill(255,255,0) # set color for objects: red, green, blue
app.rect(100,100,200,100) # draw a rectangle: x0, y0, size_x, size_y
app.fill(0,0,255) # set color for objects: red, green, blue
app.ellipse(300,200,50,50) # draw a circle: center_x, center_y, size_x, size_y
app.redraw() # refresh the window


Python 3.7.9 (bundled)
>>> %Run thonneyProcessingPy.py
Starting App...
>> Exception in thread "main" java.lang.UnsupportedClassVersionError: jycessing/Runner : Unsupported major.minor version 51.0
>> 	at java.lang.ClassLoader.defineClass1(Native Method)
>> 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
>> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
>> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
>> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
>> 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
>> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
>> 	at java.security.AccessController.doPrivileged(Native Method)
>> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
>> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
>> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
>> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
>>>
--------
As far as I understood there may be a general problem concerning Jython ?
It if this should be the case then it is a pity that processing-py cannot be used.

**Comment by FarukHammoud** [comment]
> ## Thanks for the upgrade to processing-py 0.3.1. It is still not working, again errors appear...
> :-(
> I use Thonney 3.3.1 , a python IDE, https://thonney.org, where you can easily install
> packages from: Install from PyPI.
> Thonney says ist uses Python 3.7.9
> I use this example
> from processing_py import *
> 
> app = App(600,400) # create window: width, height
> app.background(0,0,0) # set background: red, green, blue
> app.fill(255,255,0) # set color for objects: red, green, blue
> app.rect(100,100,200,100) # draw a rectangle: x0, y0, size_x, size_y
> app.fill(0,0,255) # set color for objects: red, green, blue
> app.ellipse(300,200,50,50) # draw a circle: center_x, center_y, size_x, size_y
> app.redraw() # refresh the window
> 
> Python 3.7.9 (bundled)
> 
> > > > %Run thonneyProcessingPy.py
> > > > Starting App...
> > > > Exception in thread "main" java.lang.UnsupportedClassVersionError: jycessing/Runner : Unsupported major.minor version 51.0
> > > > at java.lang.ClassLoader.defineClass1(Native Method)
> > > > at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
> > > > at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
> > > > at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> > > > at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> > > > at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> > > > at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> > > > at java.security.AccessController.doPrivileged(Native Method)
> > > > at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> > > > at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> > > > at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
> > > > at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> 
> As far as I understood there may be a general problem concerning Jython ?
> It if this should be the case then it is a pity that processing-py cannot be used.

Yeap, there is this general problem with Jython regarding illegal reflective access operations, it really doesn`t work on the new versions of Java (actually in version jre-8u271). What we can do is download the jre-8u202, the last that works correctely here.

**Comment by FarukHammoud** [comment]
> > ## Thanks for the upgrade to processing-py 0.3.1. It is still not working, again errors appear...
> > :-(
> > I use Thonney 3.3.1 , a python IDE, https://thonney.org, where you can easily install
> > packages from: Install from PyPI.
> > Thonney says ist uses Python 3.7.9
> > I use this example
> > from processing_py import *
> > app = App(600,400) # create window: width, height
> > app.background(0,0,0) # set background: red, green, blue
> > app.fill(255,255,0) # set color for objects: red, green, blue
> > app.rect(100,100,200,100) # draw a rectangle: x0, y0, size_x, size_y
> > app.fill(0,0,255) # set color for objects: red, green, blue
> > app.ellipse(300,200,50,50) # draw a circle: center_x, center_y, size_x, size_y
> > app.redraw() # refresh the window
> > Python 3.7.9 (bundled)
> > > > > %Run thonneyProcessingPy.py
> > > > > Starting App...
> > > > > Exception in thread "main" java.lang.UnsupportedClassVersionError: jycessing/Runner : Unsupported major.minor version 51.0
> > > > > at java.lang.ClassLoader.defineClass1(Native Method)
> > > > > at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
> > > > > at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
> > > > > at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> > > > > at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> > > > > at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> > > > > at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> > > > > at java.security.AccessController.doPrivileged(Native Method)
> > > > > at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> > > > > at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> > > > > at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
> > > > > at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> > 
> > 
> > As far as I understood there may be a general problem concerning Jython ?
> > It if this should be the case then it is a pity that processing-py cannot be used.
> 
> Yeap, there is this general problem with Jython regarding illegal reflective access operations, it really doesn`t work on the new versions of Java (actually in version jre-8u271). What we can do is download the jre-8u202, the last that works correctely here.

I added a issues section on readme for that.

**Comment by FarukHammoud** [comment]
I'll close this issue because we have included a script to download jre-8u202 when the first code runs in the package.

**Comment by 01Griffin** [comment]
P3D example?
