### ISSUE TITLE
Why does anyone need this repo? What does it do that jdf/processing.py doesn't?

### ISSUE THREAD

**Issue by cyrusadkisson** [FarukHammoud/processing_py#4]
Not trying be snarky. Actual question. Why did you make this repo?

And why doesn't self.app.filter(BLUR) work? Is filter() not supported?

**Comment by FarukHammoud** [comment]
Actually, this repo is based on jdf's. This package is really just a python binder for his project, that makes possible to use it inside a normal python environment. 

By the way, thank you for reporting the problem with the filter, i'll look at it as soon as I can.

**Comment by cyrusadkisson** [comment]
So I think my understanding is that Processing (core) is supposed to be a coding teaching tool first and foremost and comes with its own IDE and language to facilitate that, greatly simplifying the alternative which is spinning up one's own IDE and using the base canvas/image tools in, uh, Java, I guess?

Then jdf/processing.py does the same thing but enables Python instead of the Processing language. Still keeps a dedicated IDE, though.

Then your repo, processing_py strips out the IDE? 

Do I have this right?

**Comment by FarukHammoud** [comment]
Yeap, it was already possible to use jdf's processing.py as a command-line tool. I simply adapted it to a python package, so it could be used like tkinter package, but with newer and better graphics.
