### ISSUE TITLE
Which version of Processing this is?

### ISSUE THREAD

**Issue by arisliang** [FarukHammoud/processing_py#5]
Which version this is? Possible to add a __version__ in the package?

**Comment by FarukHammoud** [comment]
I'm not sure I've understood the question. What do you mean for add a version?

**Comment by arisliang** [comment]
I mean the \_\_version\_\_ method

**Comment by FarukHammoud** [comment]
Sure! This package is distributed using the PyPI repo (https://pypi.org/project/processing-py/). You can always check the current version and Release history there.
